### PR TITLE
Implementing Browserify

### LINKED ISSUE #7: Setup Browserify

### PR DESCRIPTION
**Pull request by connorcartwright**
Fixes #7 

Hey @AurelioDeRosa 

I've just started working on this and have moved the modal `resize` and `close` functions to separate files and then `required` them where they were used.

Using `browserify` should I start splitting up functionality into smaller files?

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Yes, separate them based on their responsibility/aim.

**Comment by connorcartwright** [comment]
Hey @AurelioDeRosa

I've made a lot of progress with this - I've improved the code quality as I've been separating out the various parts of the modals functionality.

There's still some work to do, but what do you think about the structure so far?

I've separated the `embed` and `question` modals, and within the `question` modal I have further separated events (currently for `input-output` and `multiple-choice`).

Any feedback you have would be greatly appreciated :smiley:

**Comment by connorcartwright** [comment]
Hey @AurelioDeRosa 

I've updated the `embed` modal as well as updating the `ajax` requests (fixes #4).

I've simplified the layout so that all of the `multiple choice`, `hint`, `type-change`, and `input-output` events are in singular files within the events folder.

**Comment by AurelioDeRosa** [comment]
Hey @ConnorCartwright. I've submitted  a couple of commits to improve the code a bit. I'm going to send a few more before the end of today.

In general is not a good practice to have the `require`s inline. If you were doing it to have some sort of optimization (e.g. lazy loading of the module), keep in mind that Browserify puts them at the begin of the file anyway. Finally, having them at the beginning of the file helps in keeping track of the dependencies  of a module.

Also, you don't need to wrap them inside a function to call them (as you were doing in `modals.js`). Look at my commit to see how I've changed the file.

**Comment by AurelioDeRosa** [comment]
Also, some of the methods are still very related but in different files. For example, `modal-close.js` and `modal-resize.js` both do stuff with a modal. I'd have  them inside a `modal.js` file that exports both the methods.

I'm going to do this change for these two files, but it's good to review the code to combine other related methods. Having said that, let's try to complete this PR and merge it into the code base.

**Comment by AurelioDeRosa** [comment]
Another thing I've noticed is that there are still files that have all the functions wrapped inside an IIFE.  Browserify will give us only one file. If you need to run something after the DOM is loaded, you can either move the JS distribution file at the end of the file or only wrap the entry point inside the IIFE.

**Comment by connorcartwright** [comment]
Hey @AurelioDeRosa 

I've updated the code to remove the IIFEs. 

The `setup.js` file needed to be executed when the DOM loaded, so I've set the `module.exports` to execute the `setup()` function. 

Is this a good approach, or would it be better, as you suggested to wrap just that one line, `setup();`, in an IIFE?

**Comment by connorcartwright** [comment]
I think after that potentially final change this PR is good to be merged and we can further refactor closer to the end.

**Pull request merged**
